name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    run-on: ubuntu-latesd
    env: 
      SERVICE_ACCOUNT_KEY: ${{ secretes.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and ctivating virtualenv
        uses: |
          pip3 install virtualenv
          virtualenv venv
          soruce venv/bin/activate
      - name: Install dependencies
        run: |
          pip install dvc[s3]
          pip install -r requeriments_test.txt
      - name: Test API
        run: 
          export GOOGLE_APPLICATION_CREDENTIALDS=${python utilities/setter.py}
          dvc pull model/model.pkl -r model
          pytest test.py